# Generated by Django 4.2.7 on 2023-11-21 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0003_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 13, 17, 12, 490717, tzinfo=datetime.timezone.utc))),
            ],
            bases=('authtoken.token',),
        ),
    ]
