# Generated by Django 4.2.7 on 2023-12-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
