# Generated by Django 4.2.6 on 2023-11-02 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.TextField(choices=[('Read', 'Read'), ('Reading', ' Reading'), ('Unread', 'Unread'), ('Want to Buy', 'Want to Buy')])),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
