# Generated by Django 4.2.7 on 2023-11-16 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be between 1 and 5'), django.core.validators.MaxValueValidator(5, message='Rating must be between 1 and 5')]),
        ),
    ]
