# Generated by Django 4.2.7 on 2023-12-09 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_customtoken'),
        ('books', '0006_alter_book_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='books.book')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='users.userprofile')),
            ],
            options={
                'unique_together': {('userprofile', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_books', through='books.BookRating', to='users.userprofile'),
        ),
    ]
