# Generated by Django 4.2.7 on 2023-12-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_rating_bookrating_book_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Historical Fiction', 'Historical Fiction'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Self-Help', 'Self-Help'), ('Business', 'Business'), ('Travel', 'Travel'), ('Cooking', 'Cooking'), ('Science', 'Science'), ('Philosophy', 'Philosophy'), ('Poetry', 'Poetry'), ('Children', 'Children'), ('Young Adult', 'Young Adult'), ('Comics', 'Comics')], default='Fantasy'),
            preserve_default=False,
        ),
    ]
